# Generated by Django 4.2.2 on 2023-06-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
